feat: [PhU-295] Extend the Account-related fields
GSVlabs/tutor-contrib-philu-extensions pull request #25
Opened 2024-06-04 15:17 UTC by DmytroAlipov

## Description

<img width="1138" alt="Знімок екрана 2024-06-04 о 16 24 34" src="https://github.com/GSVlabs/philu-edx-platform/assets/98233552/a4888603-63a5-49fc-8671-8480646f1860">

### YouTrack:
- https://youtrack.raccoongang.com/issue/PhU-295

2024-06-04 17:33 UTC, dyudyunov requested changes

2024-06-04 17:33 UTC, dyudyunov commented on tutorphilu_extensions/plugin.py
> +            "openedx-lms-common-settings",
```suggestion
            "openedx-lms-common-settings",
```

2024-06-04 19:11 UTC, DmytroAlipov commented on tutorphilu_extensions/plugin.py
> +            "openedx-lms-common-settings",
oops 🫣

2024-06-04 19:12 UTC, DmytroAlipov commented on tutorphilu_extensions/plugin.py
> +            "openedx-lms-common-settings",
done

2024-06-05 11:57 UTC, dyudyunov approved these changes

2024-06-05 12:00 UTC, merged